id: fr-FR
label: Français
translators:
  [
    "arnauddrain",
    "AvocadoVenom",
    "dragonis41",
    "AugustinMauroy",
    "keltroth",
    "dlapointegilbert",
    "benoit-dumont",
  ]
active: true
